# Auto-generated by CI — do not edit manually
cask "nebo" do
  version "0.4.1"

  on_arm do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.4.1/Nebo-0.4.1-arm64.dmg"
    sha256 "04794ebc694bc586719f2ab1347eeb5904b7b5ac219c19ff8b521abd5f0d2d3f"
  end

  on_intel do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.4.1/Nebo-0.4.1-amd64.dmg"
    sha256 "013f1debd207bf718a7b3297652d99c9e274ff3dc0d0359561a39255180a2423"
  end

  name "Nebo"
  desc "AI agent with web UI - your personal AI companion"
  homepage "https://neboloop.com"

  app "Nebo.app"

  binary "#{appdir}/Nebo.app/Contents/MacOS/Nebo"

  zap trash: [
    "~/Library/Application Support/Nebo",
  ]
end
