# Auto-generated by CI — do not edit manually
cask "nebo" do
  version "0.10.0"

  url "https://github.com/NeboLoop/nebo/releases/download/v0.10.0/Nebo-0.10.0-arm64.dmg"
  sha256 "2bc9946a69e6ba1f228d4d2fc5b104c41b3e4798b4f2defab60ff17e87ae72fd"

  name "Nebo"
  desc "AI agent with web UI - your personal AI companion"
  homepage "https://neboai.com"

  depends_on arch: :arm64

  app "Nebo.app"

  binary "#{appdir}/Nebo.app/Contents/MacOS/Nebo"

  zap trash: [
    "~/Library/Application Support/Nebo",
  ]
end
