# Auto-generated by CI — do not edit manually
cask "nebo" do
  version "0.7.0"

  on_arm do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.7.0/Nebo-0.7.0-arm64.dmg"
    sha256 "bd56e73961d380820687fdd164b153d668a63e5323c870db98a3149623477308"
  end

  on_intel do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.7.0/Nebo-0.7.0-amd64.dmg"
    sha256 "c8c6e193260f1194ea32761a24237dbc03f810d0d1387d6b80d4c08cfd2c00de"
  end

  name "Nebo"
  desc "AI agent with web UI - your personal AI companion"
  homepage "https://neboloop.com"

  app "Nebo.app"

  binary "#{appdir}/Nebo.app/Contents/MacOS/Nebo"

  zap trash: [
    "~/Library/Application Support/Nebo",
  ]
end
